### ISSUE TITLE
Not sure that Dashboard Charts show an accurate data

### ISSUE THREAD

**Issue by pzubar** [foo-software/discussion#1] opened 2021-06-09 09:26 UTC
Hello! I've just started using the Foo Software monitoring for our website's homepage. 
I followed the [instruction](https://www.foo.software/web-vitals-how-to-track-and-analyze-web-vitals/#how-to-analyze-web-vitals-with-foo) to install the web-vitals and send the statistics to foo software. Here is the screenshot of the example LCP metric sent (see the value on the right, 2400 milliseconds), while the chart is telling about 300ms as a max. The same is with FCP, btw. Am I doing something wrong?

Thank you in advance!

![image](https://user-images.githubusercontent.com/36226946/121329237-b30adc00-c91d-11eb-802e-9f248e816162.png)

**Comment by adamhenson** [comment] 2021-06-09 12:14
Hello @pzubar - thanks for trying our Web Vitals service. That number represents an average of the day. Also, if you haven’t noticed - there is a toggle at the top right to toggle between mobile and desktop data.

**Comment by pzubar** [comment] 2021-06-09 12:28
Hello @adamhenson and thanks for your response. Unfortunately, I am not sure about such a speed of the page - according to my logs, the requests are processed longer, than the FCP (and even LCP) shown there. Is it possible, that something else is wrong?

**Comment by pzubar** [comment] 2021-06-09 13:53
By the way, the numbers changed and became more unrealistic now
![image](https://user-images.githubusercontent.com/36226946/121367075-a9479f80-c942-11eb-8d10-24dffb7af855.png)

**Comment by adamhenson** [comment] 2021-06-09 15:17
Thanks for the information @pzubar and sorry for the issue. Give me 24 hours to get to the bottom of it. Will post back on this thread when I have more info.

**Comment by adamhenson** [comment] 2021-06-09 17:50
@pzubar - We've determined the problem is definitely on our end. It seems that you've set it up correctly. We will have a fix in the next 24 hours. Please note that we will clear out the bad data, so once that change is made - the start date will most likely be today in the chart.

**Comment by adamhenson** [comment] 2021-06-09 21:42
@pzubar - thanks for reporting this and your patience. The issue has been identified and resolved thanks to your report and info. The bad data has been cleared from your account (so you'll only see data for today and future). Our services is typically very stable and reliable, but I'll let you be the judge as you continue to test our services. Web Vitals is one that hasn't gotten a ton of use, but I'm hoping that will change as it becomes a more important point of analytics.

Feel free to report how things are now. And don't hesitate to reach back out with a new topic or continue on this one.

**Comment by adamhenson** [comment] 2021-06-11 15:14
Closing this for now, but if we can re-open if anything else comes up.

**Closed as completed by adamhenson** 2021-06-11 15:14 UTC

**Comment by pzubar** [comment] 2021-06-16 14:00
Thank you, @adamhenson ! I see that now the issue is fixed and everything works fine.

**Comment by adamhenson** [comment] 2021-06-16 14:12
Thanks for the follow up @pzubar!
